platform :ios, '7.0'
 
pod 'AFNetworking', '~> 2.0'
pod 'AFNetworking-RACExtensions', :git => 'https://github.com/knshiro/AFNetworking-RACExtensions.git'
pod 'MBProgressHUD', '~> 0.5'
pod 'Mantle', '~> 1.3.1'
pod 'TSMessages'
pod 'LBBlurredImage'
pod 'ReactiveCocoa'
pod 'ECSlidingViewController', '~> 2.0.1'
